source 'http://rubygems.org'

gem 'activerecord', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'sinatra'
gem 'pg'
gem 'pry'
gem 'shotgun'
gem 'rake'
gem 'rspec'
gem 'thin'
#gem 'nokogiri'
gem 'require_all'
gem 'rack-test'