source 'http://rubygems.org'

gem 'sinatra'
gem 'activerecord', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
#gem 'nokogiri'
gem 'require_all'
gem 'pg'
# gem 'sqlite3'
gem 'rspec'
gem 'rack-test'
gem 'geocoder'
gem 'pry'
gem 'shotgun'
gem 'thin'